# Plugin manager
[[plugins]]
repo = 'Shougo/dein.vim'

# complete parenthesis and etc.
[[plugins]]
#repo = 'Townk/vim-autoclose'
repo = 'cohama/lexima.vim'
hook_add = '''
    call lexima#add_rule({'char':'<', 'input_after':'>'})
    call lexima#add_rule({'char':'>', 'at':'\%#>', 'leave':1})
    call lexima#add_rule({'char':'<BS>', 'at':'<\%#>', 'delete':1})
'''

# completion framework "deoplete"
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter'
hook_add = '''
    let g:deoplete#enable_at_startup = 1
    inoremap <expr><Tab> pumvisible() ? "\<DOWN>" : "\<Tab>"
    inoremap <expr><S-Tab> pumvisible() ? "\<UP>" : "\<S-Tab>"
'''

# deoplete-plugin "jedi" 
[[plugins]]
repo = 'deoplete-plugins/deoplete-jedi'

# deoplete-plugin "clang"
#[[plugins]]
#repo = 'zchee/deoplete-clang'
#hook_source = '''
#    let g:deoplete#sources#clang#libclang_path = '/usr/lib/llvm-6.0/lib/libclang.so'
#    let g:deoplete#sources#clang#clang_header = '/usr/include/clang'
#'''

# color schemer
[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
    set background=dark
    au MyAutoCmd VimEnter * nested colorscheme hybrid
'''
